spring.application.name=voting
spring.datasource.url=jdbc:postgresql://localhost:5432/voting_database
spring.datasource.username=postgres
spring.datasource.password=damilare
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.datasource.hikari.auto-commit=false

